spring:
  datasource:
    username: java
    password: java
    url: jdbc:postgresql://localhost:5432/postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: "org.hibernate.dialect.PostgreSQL10Dialect"
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB
  mvc:
    hidden-method:
      filter:
        enabled: true
  redis:
    port: 6379
  data:
    redis:
      host: localhost

logging:
  level:
    org.springframework: trace

server:
  port: 8080

minio:
  client:
    endpoint: http://127.0.0.1:9000
    user: root
    password: rootpassword
  bucket-name: user-files