spring:
  datasource:
    username: ${SPRING_DB_USER}
    password: ${SPRING_DB_PASSWORD}
    url: ${SPRING_DB_URL}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQL10Dialect
          show_sql: true
          format_sql: true