spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: pass

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
        show_sql: true
        format_sql: true

  data:
    redis:
      host: ${SPRING_REDIS_HOST}
      port: ${SPRING_REDIS_PORT}

  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB

  mvc:
    hidden-method:
      filter:
        enabled: true

minio:
  client:
    endpoint: ${MINIO_CLIENT_ENDPOINT}
    user: ${MINIO_CLIENT_USER}
    password: ${MINIO_CLIENT_PASSWORD}
  bucket-name: user-files